version: '3.8'

services:

#  web:
#    build:
#        context: .
#        dockerfile: Dockerfile
#        args:
#          - args=${args}
#    env_file:
#      - .env
#    restart: on-failure
#    ports:
#      - ${LOCAL_PORT}:8000
#    volumes:
#      - ./src:/app
#    depends_on:
#        - db
#    command: "air --build.cmd 'go build -o ./tmp/main ./cmd/sales-api' --build.bin 'tmp/main' --build.args_bin '${args}'"

  db:
    container_name: sales_db
    image: postgres:15.2-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGUSER=${DB_USER}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}'"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 1s


volumes:
  postgres-db: